### ISSUE TITLE
Naming of slack variables?

### ISSUE THREAD

**Issue by dourouc05** [JuliaOpt/Dualization.jl#32]
I am dualising a model with nonnegative variables, so I expect to have dual constraints `>= 0`, but I have slack variables. I did not see a way of disabling these slack variables (or is there a reason they are used?).

The "meat" of this issue: these slack variables have no real name, I see things like `_1` and `_1_1` when exporting the dual model through MathOptFormat.jl (I suspect that the second name comes from renaming to ensure that all variables have distinct names without forbidden symbols when exporting to LP). Would it be possible to automatically name those slack variables? Like `slack_var1` for the dual constraint associated with the primal variable `var1`.

**Comment by blegat** [comment]
> I am dualising a model with nonnegative variables, so I expect to have dual constraints `>= 0`, but I have slack variables. I did not see a way of disabling these slack variables (or is there a reason they are used?).

See https://github.com/guilhermebodin/Dualization.jl/issues/9

**Comment by guilhermebodin** [comment]
For the naming you can try this `dualize(primal_model, dual_names = Dualization.DualNames("", "slack_var")`. With this dual_names variable, you can change the prefix for the dual variable associated with primal constraint and also for the dual constraint associated with the primal variables.

**Comment by dourouc05** [comment]
It doesn't seem to work as expected… Here, `s_m` is a JuMP model: 

`dualize(backend(s_m), dual_names=Dualization.DualNames("", "slack_var"))`

In the LP file (or if I convert the MOI model into a JuMP model), I still get names like `_1`.

(By the way, could you make the first part of https://github.com/guilhermebodin/Dualization.jl/blob/master/test/optimize_abstract_models.jl#L5 a standalone function to get a JuMP model? Maybe both from a ModelLike and directly from a DualProblem?)

**Comment by guilhermebodin** [comment]
Yes, that's in the plan, input a JuMP model and output a dualized JuMP model :) 

Could you share the script of this model so I can get more intuition on what is not working properly?

**Comment by dourouc05** [comment]
I'm trying to reduce it (in order not to send you a few thousands lines of code 😛).
