### ISSUE TITLE
Don't allow DataType as type of argument

### ISSUE THREAD

**Issue by guilhermebodin** [JuliaOpt/Dualization.jl#54]
In the code many times we have functions like `supported_constraints(con_types::Vector{Tuple{DataType, DataType}})`
We should change this to something more clear

**Comment by blegat** [comment]
What would you change it too ? We use `Vector{Tuple{DataType, DataType}}` for value of `MOI.ListOfConstraints`

**Comment by guilhermebodin** [comment]
I thought I could do something like 
```julia
function supported_constraints(con_types::Vector{Tuple{DataType, DataType}})
    for (F, S) in con_types
        if !supported_constraint(F, S)
        end
    end
    return 
end
supported_constraint(::DataType, ::DataType) = false

function supported_constraints2(con_types::Vector{Tuple{Type{<:MOI.AbstractFunction}, Type{<:MOI.AbstractSet}}})
    for (F, S) in con_types
        if !supported_constraint2(F, S)
        end
    end
    return 
end
supported_constraint2(::Type{<:MOI.AbstractFunction}, ::Type{<:MOI.AbstractSet}) = false
```
but actually I can't.

**Comment by blegat** [comment]
This is tricky indeed, conversion does not always work between the two. See https://github.com/JuliaOpt/MathOptInterface.jl/issues/783
