### ISSUE TITLE
MOIU._hasvar not defined error

### ISSUE THREAD

**Issue by bcdandurand** [JuliaOpt/Dualization.jl#71]
I get an error from line 103
 `if MOIU._hasvar(term, variable_parameters)`
of `objective_coefficients.jl` indicating that `_hasvar` is not defined. Is this perhaps a deprecated function of the MOI Utilities?

**Comment by bcdandurand** [comment]
I'm using the most recent version of MOI as of this posting.

**Comment by blegat** [comment]
This is due to https://github.com/JuliaOpt/MathOptInterface.jl/pull/983
