### ISSUE TITLE
supports_constraint

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/Dualization.jl#77]
`supports_constraint` of `DualOptimizer` simply redirects the same call the the underlying solver. This is incorrect.
Instead, we should have:
* `supports_constraint` of `Union{VectorOfVariables, VectorAffineFunction}`-in-`K` -> `supports_constrained_variable`-in-`dual_set_type(K)` (see https://github.com/JuliaOpt/MathOptInterface.jl/issues/987)
* `supports_constrained_variable` in `K` -> `supports_constraint` of `VectorAffineFunction`-in-`K`

**Comment by guilhermebodin** [comment]
So let me see if I got this right, we should replace
```julia
function MOI.supports_constraint(optimizer::DualOptimizer, F::Type{<:SF}, S::Type{<:SS})
    return MOI.supports_constraint(optimizer.dual_problem.dual_model, F, S)
end
```
by two functions would those be `supports_add_constrained_variable` and `supports_add_constrained_variables` from this PR https://github.com/JuliaOpt/MathOptInterface.jl/pull/1004?

**Comment by blegat** [comment]
No, we should keep supports_constraint but replace change its implementation. It should take into account that it dualizes the problem0
